### PR TITLE
Fix module compilation warning and clarify FFI pointer operations

### PR DESCRIPTION
**Pull request by tathanhdinh**

### CODE REVIEW

**Comment by jbaublitz** [comment]
Hi and thanks for the PR. Given that this has no description, I'm assuming this is not a bug report and fix. As a result, I do expect an explanation of how your changes provide improvements whether that is based on clarity, correctness, or some other technical basis. I'm happy to work with you on this but as it stands I don't have any explanation for the purpose of these changes. Would you be willing to provide a longer explanation of what this adds from your perspective?

**Comment by tathanhdinh** [comment]
@jbaublitz thank you for the feedback and sorry for lacking of description. I'm learning how to write a Linux kernel module in Rust and found your project.

This PR is really trivial, it mostly changes:

https://github.com/jbaublitz/knock-out/blob/42ca50c4f899e6fca6f3a2f68a55485423a1f193/src/lib.rs#L97-L102

into

```rust
        unsafe {
            parrot_owner_ptr.write(Self::owner());
            parrot_read_ptr.write(read);
            parrot_open_ptr.write(open);
            parrot_release_ptr.write(release);
        }
```

and add

```
MODULE_LICENSE("GPL v2");
```

into `ffi.c` to avoid the warning: 

```bash
WARNING: modpost: missing MODULE_LICENSE() in /repos/knock-out/parrot.o
```

each time we run make.

**Comment by jbaublitz** [comment]
I appreciate you giving me the context here. Given that this is mainly meant to be an educational project, I would prefer the following before merging:
* A new descriptive title such as "Fix module compilation warning and clarify FFI pointer operations"
* All other changes removed unless there is a reason that you have for adding them that you have not specified above
* Rebase and make the commit message descriptive of the change (I have not always been good about this and am trying to do better as it has consequences when maintaining code)

I'm aiming for clarity above all in this project and just as you're learning now, it will be important for others to see why changes have been made if they stumble across this project too. Thanks!

**Comment by tathanhdinh** [comment]
Thank you for the constructive response. I've changed the PR to fit the requirement.

**Comment by jbaublitz** [comment]
Excellent, thanks so much! I'm going to test on my end and as long as party parrot still parties, I'll merge it.

**Pull request merged**
